name: grassland
description: Generate 3d grass image from github contributions grid

inputs:
  github_username:
    description: "GitHub username which contributions grid to use for generating image"
    required: true
  
  github_token:
    description: "GitHub token for fetching contributions grid"
    required: true
  
  command:
    description: "Command to select the type of configuration"
    required: true

  argument:
    description: "Argument to select the configuration file"
    required: true

  output_path:
    description: "Path to output image"
    required: false
    default: "dist/output.png"

runs:
  using: "composite"
  steps:
    - name: Cache Blender
      id: cache-blender
      uses: actions/cache@v4
      with:
        path: blender-4.2.3-linux-x64
        key: ${{ runner.os }}-blender-4.2.3-linux-x64

    - name: Install Blender
      if: steps.cache-blender.outputs.cache-hit != 'true'
      run: |   
          wget https://download.blender.org/release/Blender4.2/blender-4.2.3-linux-x64.tar.xz -q
          tar -xf blender-4.2.3-linux-x64.tar.xz
      shell: bash
          
    - name: Generate Picture
      run: >
          ./blender-4.2.3-linux-x64/blender
          --background
          --threads 0
          -noaudio
          --python $GITHUB_ACTION_PATH/src/main.py
          -- 
          -b $GITHUB_ACTION_PATH/assets/objects.blend
          -o ${{ inputs.output_path }}
          -t $GITHUB_ACTION_PATH/themes
          ${{ inputs.command }}
          ${{ inputs.argument }}
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        GITHUB_USERNAME: ${{ inputs.github_username }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
