
[ground.material.GroundNone]
color0 = [0.9, 0.5, 0.7, 1.0]
color1 = [0.8, 0.3, 0.6, 1.0]

[ground.material.GroundFirst]
color0 = [0.7, 0.4, 0.6, 1.0]
color1 = [0.6, 0.2, 0.5, 1.0]

[ground.material.GroundSecond]
color0 = [0.5, 0.3, 0.4, 1.0]
color1 = [0.4, 0.1, 0.3, 1.0]

[ground.material.GroundThird]
color0 = [0.3, 0.2, 0.3, 1.0]
color1 = [0.2, 0.0, 0.2, 1.0]

[ground.material.GroundFourth]
color0 = [0.3, 0.1, 0.1, 1.0]
color1 = [0.0, 0.0, 0.0, 1.0]

[grass.material.GrassNone]
color0 = [0.1, 0.9, 0.6, 1.0]
color1 = [0.1, 0.9, 0.6, 1.0]
[grass.object.none]
z_scale = 0.0
density = 0.0

[grass.material.GrassFirst]
color0 = [0.1, 0.8, 0.5, 1.0]
color1 = [0.1, 0.8, 0.5, 1.0]
[grass.object.first_quartile]
z_scale = 0.2
density = 0.8

[grass.material.GrassSecond]
color0 = [0.1, 0.7, 0.4, 1.0]
color1 = [0.1, 0.7, 0.4, 1.0]
[grass.object.second_quartile]
z_scale = 0.5
density = 2

[grass.material.GrassThird]
color0 = [0.1, 0.6, 0.3, 1.0]
color1 = [0.1, 0.6, 0.3, 1.0]
[grass.object.third_quartile]
z_scale = 0.7
density = 3

[grass.material.GrassFourth]
color0 = [0.1, 0.1, 0.1, 1.0]
color1 = [0.0, 0.0, 0.0, 1.0]
[grass.object.fourth_quartile]
z_scale = 1.2
density = 4
