[ground]
GroundNone.color0 = [0.9, 0.5, 0.7, 1.0]
GroundNone.color1 = [0.8, 0.3, 0.6, 1.0]
GroundFirst.color0 = [0.7, 0.4, 0.6, 1.0]
GroundFirst.color1 = [0.6, 0.2, 0.5, 1.0]
GroundSecond.color0 = [0.5, 0.3, 0.4, 1.0]
GroundSecond.color1 = [0.4, 0.1, 0.3, 1.0]
GroundThird.color0 = [0.3, 0.2, 0.3, 1.0]
GroundThird.color1 = [0.2, 0.0, 0.2, 1.0]
GroundFourth.color0 = [0.1, 0.1, 0.1, 1.0]
GroundFourth.color1 = [0.0, 0.0, 0.0, 1.0]
