name: Generate Picture and Push to output branch

on:
    push:
        branches:
            - main

jobs:
    generate:
        runs-on: ubuntu-24.04

        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Install dependencies
            run: |
                wget https://download.blender.org/release/Blender4.2/blender-4.2.3-linux-x64.tar.xz
                tar -xvf blender-4.2.3-linux-x64.tar.xz

          - name: Generate Picture
            run: ./blender-4.2.3-linux-x64/blender --background --threads 0 -noaudio --python add.py
            env:
                GITHUB_USERNAME: ${{ github.repository_owner }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          - name: Commit and push to output branch
            run: |
                git config --global user.email "actions@github.com"
                git config --global user.name "GitHub Actions"
                git push --delete origin output || true
                git checkout -b output
                git add -f output.png
                git commit -m "Add output.png"
                git push origin output



                
                

    