name: Generate Picture and Push to output branch

on:
    push:
        branches:
            - main

jobs:
    generate:
        runs-on: ubuntu-24.04

        steps:
          - name: Checkout
            uses: actions/checkout@v4

          # - name: Install dependencies
          #   run: |
          #       wget https://download.blender.org/release/Blender4.2/blender-4.2.3-linux-x64.tar.xz
          #       tar -xvf blender-4.2.3-linux-x64.tar.xz

          # - name: Generate Picture
          #   run: ./blender-4.2.3-linux-x64/blender --background --threads 0 -noaudio --python add.py

          - name: Generate Picture
            uses: ry05k2ulv/grassland@main
            env:
                GITHUB_USERNAME: ${{ github.repository_owner }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          - name: Push output image to output branch
            uses: crazy-max/ghaction-github-pages@v4
            with:
                target_branch: output
                build_dir: dist
                commit_message: "Generate Output Image"
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



                
                

    