name: Generate Picture and Push to output branch

on:
    push:
        branches:
            - master
            - actions

jobs:
    generate:
        runs-on: ubuntu-24.04

        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Install dependencies
            run: apt-get install -y blender

          - name: Generate Picture
            run: blender -b -P add.py

          - name: Commit and push to output branch
            run: |
                git config --global user.email "actions@github.com"
                git config --global user.name "GitHub Actions"
                git checkout -b output
                git add output.png
                git commit -m "Add output.png"
                git push origin output

                

                
                

    